[package]
name = "async-json-rpc"
version = "0.1.0"
authors = ["Harry Barber <harrybarber@protonmail.com>"]
edition = "2018"

[dependencies]
base64 = "0.11.0"
futures-core = "0.3.4"
futures-util = "0.3.4"
hyper = { version = "0.13.2", features = ["stream"] }
hyper-tls = "0.4.1"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
tower-service = "0.3.0"
