[package]
name = "async-json-rpc"
version = "0.1.0"
authors = ["Harry Barber <harrybarber@protonmail.com>"]
edition = "2018"

[dependencies]
futures-core = "0.3.1"
futures-util = "0.3.1"
hyper = { version = "0.13.0", features = ["stream"] }
hyper-tls = "0.4"
serde = { version = "1.0.103", features = ["derive"] }
serde_json = "1.0.44"
tower-service = "0.3.0"
